article:
    type: tech # tech | story
    auto_cover: true
    auto_banner: true

    share: [wechat, weibo, email, link]

    related_posts:
        # 复制 hexo-theme-stellar 到 themes 目录下，会导致 hexo-related-popular-posts 查找文件时路径出错
        enable: true
        title: 您可能感兴趣的文章

comments:
    service: utterances # beaudar, utterances, giscus, twikoo, waline, artalk
    comment_title: 快来参与讨论吧~
    # utterances
    # https://utteranc.es/
    utterances:
        repo: stephenykk/discussion
        issue-term: pathname
        issue-number:
        theme: preferred-color-scheme
        label: